title: Aimini
description: > # this means to ignore newlines until "baseurl:"
  Share my experince.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Aimini # add your name
author-img: aimini.jpg # add your photo
about-author: | 
  NCU Student, love C++, But using 
  <p>Java(Because of course)<br/>  
  Python<br/> 
  Racket<br/> 
  js<br/></p> now.

#twitter: # add your Twitter handle
#facebook: # add your Facebook handle
github: Aimini # add your Github handle
#linkedin: # add your Linkedin handle
email: 2026084033@qq.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
